---
- name: Check if the remote directory is empty
  command: "ls -A \"{{ dir_info.src }}\""
  register: dir_contents
  failed_when: dir_contents.rc != 0 and dir_contents.stderr.find('No such file or directory') == -1

- name: Set fact indicating if the directory is empty
  set_fact:
    is_remote_dir_empty: "{{ dir_contents.stdout == '' }}"

- name: Find the most recent file from a remote directory
  find:
    paths: "{{ dir_info.src }}"
    recurse: no
    age_stamp: mtime
    file_type: file
  register: find_result

- name: Set the most recent file as a fact
  set_fact:
    most_recent_file: "{{ (find_result.files | sort(attribute='mtime', reverse=True) | first) if find_result.files else None }}"

- name: Check if the file already exists locally
  stat:
    path: "{{ dir_info.dest }}/{{ most_recent_file.path | basename }}"
  register: stat_result
  when:
    - not is_remote_dir_empty
    - most_recent_file is defined

- name: Copy the most recent file from remote host to local machine if not already present
  fetch:
    src: "{{ most_recent_file.path }}"
    dest: "../{{ dir_info.dest }}/{{ most_recent_file.path | basename }}"
    flat: yes
  when:
    - not is_remote_dir_empty
    - most_recent_file is defined
    - not stat_result.stat.exists
