all:
  hosts:
    host1:
      ansible_host: 10.32.73.43
      ansible_user: andrew
      directories:
      - dest: src/Machines/Savannah/data(sav)/Pressure-Data
        src: /Users/andrew/Desktop/Pressure-Data2
      - dest: src/Machines/Savannah/data(sav)/Heating-Data
        src: /Users/andrew/Desktop/Heating-Data2
      toolname: sav
