all:
  hosts:
    host1:
      ansible_host: 192.168.1.101
      ansible_user: your_user
      file_location: /path
    host2:
      ansible_host: 192.168.1.101
      ansible_user: your_user
      file_location: /path