---
- name: Copy files from remote hosts to local machine
  hosts: all
  gather_facts: no

  tasks:
    - name: Iterate over directories
      include_tasks: fetch_files.yml
      loop: "{{ directories }}"
      loop_control:
        loop_var: dir_info